### ISSUE TITLE
master doesn't build due to SNAPSHOT dependency

### ISSUE THREAD

**Issue by raboof** [woq-blended/blended#104]
master currently doesn't build out-of-the-box because it depends on 1.1.3-SNAPSHOT of 'domino'. Is that intentional? It seems to compile fine with 1.1.2.

**Comment by atooni** [comment]
Hi, 

not building wasnẗ intentional. I had switched to a non released version of domino which provides more logging when it is waiting on stuff. I have switched back to 1.1.2 on mastre now and have pushed my experiments to the domino branch. 

Thx for reporting :)
