### ISSUE TITLE
Upgrade to Scala 2.11

### ISSUE THREAD

**Issue by atooni** [woq-blended/blended#23]

**Comment by lefou** [comment]
IMHO, since we moved to Domino 1.1, there is no other reason to stay on Scala 2.10.

Also, I ogle to try or at least experiment with ficus, a Scala API + extension around Typesafe Config, which is only released for Scala 2.11 in it's latest version.

**Comment by lefou** [comment]
Depends on #13

**Comment by lefou** [comment]
Done. We removed Neo4j completely.
