### ISSUE TITLE
Create packaging for new sample container

### ISSUE THREAD

**Issue by atooni** [woq-blended/blended#38]
Create a tar file with the runable container (bootstrap profile)

**Comment by lefou** [comment]
Depends on #32

**Comment by lefou** [comment]
in project `blended-launcher-demo` we now build two artifacts (select via classifier):

* `product` (zip) - contains the full profile which can be unpacked into the `${BLENDED_HOME}/profiles` directory
* `full-nojre` (zip, tar.gz) - contains a full runnable blended installation
