### ISSUE TITLE
Enable full docker-based test chain on TravisCI

### ISSUE THREAD

**Issue by lefou** [woq-blended/blended#62]
It should just work with this new feature: http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

**Comment by atooni** [comment]
We are leaving this for now. Travis has some restrictions regarding disk space / build time, so that we cannot run the complete build chain in travis in one go with fresh repositories. 

We are currently examining Jenkins 2.0 and it's pipeline model.
